// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBblbIJCWDm0qJQe638xzaOU9eS4ea3xac',
    appId: '1:615784427670:web:2888016b7239046dc3d2b7',
    messagingSenderId: '615784427670',
    projectId: 'oneseen-ef64d',
    authDomain: 'oneseen-ef64d.firebaseapp.com',
    storageBucket: 'oneseen-ef64d.firebasestorage.app',
    measurementId: 'G-L8CTHYR3FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGunEWjYXUShctbGyMW63bzYpIKbBJvyQ',
    appId: '1:615784427670:android:c718e36d53aab100c3d2b7',
    messagingSenderId: '615784427670',
    projectId: 'oneseen-ef64d',
    storageBucket: 'oneseen-ef64d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9M4fJvqANhkwh2qlKZinWs93hRQPfwrU',
    appId: '1:615784427670:ios:01a485b12ab19ab7c3d2b7',
    messagingSenderId: '615784427670',
    projectId: 'oneseen-ef64d',
    storageBucket: 'oneseen-ef64d.firebasestorage.app',
    iosBundleId: 'com.example.oneseen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9M4fJvqANhkwh2qlKZinWs93hRQPfwrU',
    appId: '1:615784427670:ios:01a485b12ab19ab7c3d2b7',
    messagingSenderId: '615784427670',
    projectId: 'oneseen-ef64d',
    storageBucket: 'oneseen-ef64d.firebasestorage.app',
    iosBundleId: 'com.example.oneseen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBblbIJCWDm0qJQe638xzaOU9eS4ea3xac',
    appId: '1:615784427670:web:e7f56d7376a782dac3d2b7',
    messagingSenderId: '615784427670',
    projectId: 'oneseen-ef64d',
    authDomain: 'oneseen-ef64d.firebaseapp.com',
    storageBucket: 'oneseen-ef64d.firebasestorage.app',
    measurementId: 'G-562M5NKV3L',
  );
}
